// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using YemekKalori.DAL.Context;

#nullable disable

namespace YemekKalori.DAL.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20231203173733_initfinal")]
    partial class initfinal
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("YemekKalori.Domain.Entities.Food", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<decimal>("Calorie")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CarbRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("FatRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("FoodPic")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PortionDesc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ProteinRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Foods", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Calorie = 155m,
                            CarbRate = 1.1m,
                            CreatedDate = new DateTime(2023, 12, 3, 20, 37, 33, 69, DateTimeKind.Local).AddTicks(7897),
                            FatRate = 10.6m,
                            FoodPic = "Images/HaşlanmışYumurta.jpg",
                            Name = "Haşlanmış Yumurta",
                            PortionDesc = "Adet",
                            ProteinRate = 12.6m,
                            Status = 1,
                            Type = 5
                        },
                        new
                        {
                            Id = 2,
                            Calorie = 264m,
                            CarbRate = 1.4m,
                            CreatedDate = new DateTime(2023, 12, 3, 20, 37, 33, 69, DateTimeKind.Local).AddTicks(7902),
                            FatRate = 21m,
                            FoodPic = "Images/BeyazPeynir.jpg",
                            Name = "Peynir",
                            PortionDesc = "100 gram",
                            ProteinRate = 18m,
                            Status = 1,
                            Type = 4
                        },
                        new
                        {
                            Id = 3,
                            Calorie = 115m,
                            CarbRate = 6m,
                            CreatedDate = new DateTime(2023, 12, 3, 20, 37, 33, 69, DateTimeKind.Local).AddTicks(7904),
                            FatRate = 11m,
                            FoodPic = "Images/siyah-zeytin.jpeg",
                            Name = "Siyah Zeytin",
                            PortionDesc = "100 gram",
                            ProteinRate = 0.8m,
                            Status = 1,
                            Type = 2
                        },
                        new
                        {
                            Id = 4,
                            Calorie = 145m,
                            CarbRate = 3.8m,
                            CreatedDate = new DateTime(2023, 12, 3, 20, 37, 33, 69, DateTimeKind.Local).AddTicks(7905),
                            FatRate = 15.3m,
                            FoodPic = "Images/YesilZeytin.png",
                            Name = "Yeşil Zeytin",
                            PortionDesc = "100 gram",
                            ProteinRate = 1m,
                            Status = 1,
                            Type = 2
                        },
                        new
                        {
                            Id = 5,
                            Calorie = 196m,
                            CarbRate = 1.1m,
                            CreatedDate = new DateTime(2023, 12, 3, 20, 37, 33, 69, DateTimeKind.Local).AddTicks(7908),
                            FatRate = 15m,
                            FoodPic = "Images/SahandaYumurta.png",
                            Name = "Sahanda Yumurta",
                            PortionDesc = "Adet",
                            ProteinRate = 14m,
                            Status = 1,
                            Type = 5
                        },
                        new
                        {
                            Id = 6,
                            Calorie = 106m,
                            CarbRate = 10m,
                            CreatedDate = new DateTime(2023, 12, 3, 20, 37, 33, 69, DateTimeKind.Local).AddTicks(7909),
                            FatRate = 4.9m,
                            FoodPic = "Images/Menemen.jpg",
                            Name = "Menemen",
                            PortionDesc = "100 gram",
                            ProteinRate = 6.4m,
                            Status = 1,
                            Type = 5
                        },
                        new
                        {
                            Id = 7,
                            Calorie = 266m,
                            CarbRate = 67m,
                            CreatedDate = new DateTime(2023, 12, 3, 20, 37, 33, 69, DateTimeKind.Local).AddTicks(7911),
                            FatRate = 0.2m,
                            FoodPic = "Images/Reçel.jpg",
                            Name = "Reçel",
                            PortionDesc = "100 gram",
                            ProteinRate = 0.3m,
                            Status = 1,
                            Type = 1
                        },
                        new
                        {
                            Id = 8,
                            Calorie = 304m,
                            CarbRate = 82m,
                            CreatedDate = new DateTime(2023, 12, 3, 20, 37, 33, 69, DateTimeKind.Local).AddTicks(7912),
                            FatRate = 0m,
                            FoodPic = "Images/bal.png",
                            Name = "Bal",
                            PortionDesc = "100 gram",
                            ProteinRate = 0.3m,
                            Status = 1,
                            Type = 8
                        },
                        new
                        {
                            Id = 9,
                            Calorie = 336m,
                            CarbRate = 1.4m,
                            CreatedDate = new DateTime(2023, 12, 3, 20, 37, 33, 69, DateTimeKind.Local).AddTicks(7914),
                            FatRate = 30m,
                            FoodPic = "Images/salam.png",
                            Name = "Salam",
                            PortionDesc = "100 gram",
                            ProteinRate = 13m,
                            Status = 1,
                            Type = 3
                        },
                        new
                        {
                            Id = 10,
                            Calorie = 1m,
                            CarbRate = 0.3m,
                            CreatedDate = new DateTime(2023, 12, 3, 20, 37, 33, 69, DateTimeKind.Local).AddTicks(7915),
                            FatRate = 0m,
                            FoodPic = "Images/Çay.png",
                            Name = "Çay",
                            PortionDesc = "Bardak",
                            ProteinRate = 0m,
                            Status = 1,
                            Type = 9
                        },
                        new
                        {
                            Id = 11,
                            Calorie = 1m,
                            CarbRate = 0m,
                            CreatedDate = new DateTime(2023, 12, 3, 20, 37, 33, 69, DateTimeKind.Local).AddTicks(7917),
                            FatRate = 0m,
                            FoodPic = "Images/YesilCay.png",
                            Name = "Yeşil Çay",
                            PortionDesc = "Bardak",
                            ProteinRate = 0m,
                            Status = 1,
                            Type = 9
                        },
                        new
                        {
                            Id = 12,
                            Calorie = 45m,
                            CarbRate = 10.4m,
                            CreatedDate = new DateTime(2023, 12, 3, 20, 37, 33, 69, DateTimeKind.Local).AddTicks(7962),
                            FatRate = 0.2m,
                            FoodPic = "Images/Portakal-suyu.jpg",
                            Name = "Portakal Suyu",
                            PortionDesc = "Bardak",
                            ProteinRate = 0.7m,
                            Status = 1,
                            Type = 10
                        },
                        new
                        {
                            Id = 13,
                            Calorie = 42m,
                            CarbRate = 5m,
                            CreatedDate = new DateTime(2023, 12, 3, 20, 37, 33, 69, DateTimeKind.Local).AddTicks(7964),
                            FatRate = 1m,
                            FoodPic = "Images/Süt.jpg",
                            Name = "Süt",
                            PortionDesc = "Bardak",
                            ProteinRate = 3.4m,
                            Status = 1,
                            Type = 4
                        },
                        new
                        {
                            Id = 14,
                            Calorie = 66m,
                            CarbRate = 9.2m,
                            CreatedDate = new DateTime(2023, 12, 3, 20, 37, 33, 69, DateTimeKind.Local).AddTicks(7965),
                            FatRate = 2.2m,
                            FoodPic = "Images/MercimekCorbası.png",
                            Name = "Mercimek Çorbası",
                            PortionDesc = "100 gram",
                            ProteinRate = 4.1m,
                            Status = 1,
                            Type = 2
                        },
                        new
                        {
                            Id = 15,
                            Calorie = 39m,
                            CarbRate = 3.9m,
                            CreatedDate = new DateTime(2023, 12, 3, 20, 37, 33, 69, DateTimeKind.Local).AddTicks(7967),
                            FatRate = 1.5m,
                            FoodPic = "Images/Tavuk Çorbası.png",
                            Name = "Tavuk Çorbası",
                            PortionDesc = "100 gram",
                            ProteinRate = 2.9m,
                            Status = 1,
                            Type = 3
                        },
                        new
                        {
                            Id = 16,
                            Calorie = 32m,
                            CarbRate = 4.3m,
                            CreatedDate = new DateTime(2023, 12, 3, 20, 37, 33, 69, DateTimeKind.Local).AddTicks(7969),
                            FatRate = 1.6m,
                            FoodPic = "Images/domatesÇorbası.png",
                            Name = "Domates Çorbası",
                            PortionDesc = "100 gram",
                            ProteinRate = 1.2m,
                            Status = 1,
                            Type = 2
                        },
                        new
                        {
                            Id = 17,
                            Calorie = 40m,
                            CarbRate = 5.3m,
                            CreatedDate = new DateTime(2023, 12, 3, 20, 37, 33, 69, DateTimeKind.Local).AddTicks(7970),
                            FatRate = 1.5m,
                            FoodPic = "Images/SebzeÇorbası.jpg",
                            Name = "Sebze Çorbası",
                            PortionDesc = "100 gram",
                            ProteinRate = 1.4m,
                            Status = 1,
                            Type = 2
                        },
                        new
                        {
                            Id = 18,
                            Calorie = 130m,
                            CarbRate = 28.2m,
                            CreatedDate = new DateTime(2023, 12, 3, 20, 37, 33, 69, DateTimeKind.Local).AddTicks(7972),
                            FatRate = 0.3m,
                            FoodPic = "Images/PirinçPilavı.jpg",
                            Name = "Pirinç Pilavı",
                            PortionDesc = "100 gram",
                            ProteinRate = 2.7m,
                            Status = 1,
                            Type = 6
                        },
                        new
                        {
                            Id = 19,
                            Calorie = 83m,
                            CarbRate = 18.6m,
                            CreatedDate = new DateTime(2023, 12, 3, 20, 37, 33, 69, DateTimeKind.Local).AddTicks(7973),
                            FatRate = 0.2m,
                            FoodPic = "Images/BulgurPilavı.jpg",
                            Name = "Bulgur Pilavı",
                            PortionDesc = "100 gram",
                            ProteinRate = 3.1m,
                            Status = 1,
                            Type = 6
                        },
                        new
                        {
                            Id = 20,
                            Calorie = 131m,
                            CarbRate = 25m,
                            CreatedDate = new DateTime(2023, 12, 3, 20, 37, 33, 69, DateTimeKind.Local).AddTicks(7976),
                            FatRate = 1.1m,
                            FoodPic = "Images/Makarna.jpg",
                            Name = "Makarna",
                            PortionDesc = "100 gram",
                            ProteinRate = 5m,
                            Status = 1,
                            Type = 7
                        },
                        new
                        {
                            Id = 21,
                            Calorie = 180m,
                            CarbRate = 2m,
                            CreatedDate = new DateTime(2023, 12, 3, 20, 37, 33, 69, DateTimeKind.Local).AddTicks(7978),
                            FatRate = 8m,
                            FoodPic = "Images/Kebap.jpg",
                            Name = "Kebap",
                            PortionDesc = "100 gram",
                            ProteinRate = 25m,
                            Status = 1,
                            Type = 3
                        },
                        new
                        {
                            Id = 22,
                            Calorie = 225m,
                            CarbRate = 2.2m,
                            CreatedDate = new DateTime(2023, 12, 3, 20, 37, 33, 69, DateTimeKind.Local).AddTicks(7979),
                            FatRate = 12m,
                            FoodPic = "Images/Döner.jpg",
                            Name = "Döner",
                            PortionDesc = "100 gram",
                            ProteinRate = 26m,
                            Status = 1,
                            Type = 3
                        },
                        new
                        {
                            Id = 23,
                            Calorie = 333m,
                            CarbRate = 31.8m,
                            CreatedDate = new DateTime(2023, 12, 3, 20, 37, 33, 69, DateTimeKind.Local).AddTicks(7980),
                            FatRate = 17.8m,
                            FoodPic = "Images/Falafel.jpg",
                            Name = "Falafel",
                            PortionDesc = "100 gram",
                            ProteinRate = 13.3m,
                            Status = 1,
                            Type = 2
                        },
                        new
                        {
                            Id = 24,
                            Calorie = 254m,
                            CarbRate = 30m,
                            CreatedDate = new DateTime(2023, 12, 3, 20, 37, 33, 69, DateTimeKind.Local).AddTicks(7998),
                            FatRate = 10m,
                            FoodPic = "Images/Hamburger.png",
                            Name = "Hamburger",
                            PortionDesc = "Adet",
                            ProteinRate = 12m,
                            Status = 1,
                            Type = 3
                        },
                        new
                        {
                            Id = 25,
                            Calorie = 20m,
                            CarbRate = 4m,
                            CreatedDate = new DateTime(2023, 12, 3, 20, 37, 33, 69, DateTimeKind.Local).AddTicks(8000),
                            FatRate = 0.2m,
                            FoodPic = "Images/MevsimSalata.png",
                            Name = "Mevsim Salata",
                            PortionDesc = "100 gram",
                            ProteinRate = 1m,
                            Status = 1,
                            Type = 2
                        },
                        new
                        {
                            Id = 26,
                            Calorie = 23m,
                            CarbRate = 4.3m,
                            CreatedDate = new DateTime(2023, 12, 3, 20, 37, 33, 69, DateTimeKind.Local).AddTicks(8002),
                            FatRate = 0.4m,
                            FoodPic = "Images/coban_salatasi.jpg",
                            Name = "Çoban Salata",
                            PortionDesc = "100 gram",
                            ProteinRate = 1.1m,
                            Status = 1,
                            Type = 2
                        },
                        new
                        {
                            Id = 27,
                            Calorie = 265m,
                            CarbRate = 49m,
                            CreatedDate = new DateTime(2023, 12, 3, 20, 37, 33, 69, DateTimeKind.Local).AddTicks(8005),
                            FatRate = 3.2m,
                            FoodPic = "Images/beyaz_ekmek.jpg",
                            Name = "Beyaz Ekmek",
                            PortionDesc = "2 dilim",
                            ProteinRate = 9m,
                            Status = 1,
                            Type = 7
                        },
                        new
                        {
                            Id = 28,
                            Calorie = 247m,
                            CarbRate = 41m,
                            CreatedDate = new DateTime(2023, 12, 3, 20, 37, 33, 69, DateTimeKind.Local).AddTicks(8007),
                            FatRate = 4.2m,
                            FoodPic = "Images/kepek_ekmegi.jpg",
                            Name = "Kepekli Ekmek",
                            PortionDesc = "2 dilim",
                            ProteinRate = 13m,
                            Status = 1,
                            Type = 7
                        },
                        new
                        {
                            Id = 29,
                            Calorie = 259m,
                            CarbRate = 48.3m,
                            CreatedDate = new DateTime(2023, 12, 3, 20, 37, 33, 69, DateTimeKind.Local).AddTicks(8009),
                            FatRate = 3.3m,
                            FoodPic = "Images/cavdar_ekmegi.jpg",
                            Name = "Çavdar Ekmeği",
                            PortionDesc = "2 dilim",
                            ProteinRate = 8.5m,
                            Status = 1,
                            Type = 7
                        },
                        new
                        {
                            Id = 30,
                            Calorie = 247m,
                            CarbRate = 43.4m,
                            CreatedDate = new DateTime(2023, 12, 3, 20, 37, 33, 69, DateTimeKind.Local).AddTicks(8011),
                            FatRate = 4.4m,
                            FoodPic = "Images/tam_tahilli_ekmek.jpg",
                            Name = "Tam Tahıllı Ekmek",
                            PortionDesc = "2 dilim",
                            ProteinRate = 13m,
                            Status = 1,
                            Type = 7
                        },
                        new
                        {
                            Id = 31,
                            Calorie = 0.5m,
                            CarbRate = 0m,
                            CreatedDate = new DateTime(2023, 12, 3, 20, 37, 33, 69, DateTimeKind.Local).AddTicks(8012),
                            FatRate = 0m,
                            FoodPic = "Images/light_kola.jpg",
                            Name = "Light Cola",
                            PortionDesc = "Bardak",
                            ProteinRate = 0m,
                            Status = 1,
                            Type = 11
                        },
                        new
                        {
                            Id = 32,
                            Calorie = 48m,
                            CarbRate = 12m,
                            CreatedDate = new DateTime(2023, 12, 3, 20, 37, 33, 69, DateTimeKind.Local).AddTicks(8014),
                            FatRate = 0m,
                            FoodPic = "Images/fanta.jpg",
                            Name = "Fanta",
                            PortionDesc = "Bardak",
                            ProteinRate = 0m,
                            Status = 1,
                            Type = 11
                        },
                        new
                        {
                            Id = 33,
                            Calorie = 30m,
                            CarbRate = 7.5m,
                            CreatedDate = new DateTime(2023, 12, 3, 20, 37, 33, 69, DateTimeKind.Local).AddTicks(8016),
                            FatRate = 0m,
                            FoodPic = "Images/icetea.jpg",
                            Name = "Ice Tea",
                            PortionDesc = "Bardak",
                            ProteinRate = 0m,
                            Status = 1,
                            Type = 11
                        },
                        new
                        {
                            Id = 34,
                            Calorie = 37m,
                            CarbRate = 3.5m,
                            CreatedDate = new DateTime(2023, 12, 3, 20, 37, 33, 69, DateTimeKind.Local).AddTicks(8018),
                            FatRate = 2m,
                            FoodPic = "Images/ayran.jpg",
                            Name = "Ayran",
                            PortionDesc = "Bardak",
                            ProteinRate = 1.7m,
                            Status = 1,
                            Type = 4
                        },
                        new
                        {
                            Id = 35,
                            Calorie = 299m,
                            CarbRate = 79.2m,
                            CreatedDate = new DateTime(2023, 12, 3, 20, 37, 33, 69, DateTimeKind.Local).AddTicks(8020),
                            FatRate = 0.5m,
                            FoodPic = "kuru_uzum.jpg",
                            Name = "Kuru Üzüm",
                            PortionDesc = "100 gram",
                            ProteinRate = 3.1m,
                            Status = 1,
                            Type = 1
                        },
                        new
                        {
                            Id = 36,
                            Calorie = 241m,
                            CarbRate = 62.6m,
                            CreatedDate = new DateTime(2023, 12, 3, 20, 37, 33, 69, DateTimeKind.Local).AddTicks(8021),
                            FatRate = 0.5m,
                            FoodPic = "Images/kuru_kayisi.jpg",
                            Name = "Kuru Kayısı",
                            PortionDesc = "100 gram",
                            ProteinRate = 3.4m,
                            Status = 1,
                            Type = 1
                        },
                        new
                        {
                            Id = 37,
                            Calorie = 654m,
                            CarbRate = 13.7m,
                            CreatedDate = new DateTime(2023, 12, 3, 20, 37, 33, 69, DateTimeKind.Local).AddTicks(8023),
                            FatRate = 65.2m,
                            FoodPic = "Images/ceviz.jpg",
                            Name = "Ceviz",
                            PortionDesc = "100 gram",
                            ProteinRate = 15.2m,
                            Status = 1,
                            Type = 12
                        },
                        new
                        {
                            Id = 38,
                            Calorie = 628m,
                            CarbRate = 16.7m,
                            CreatedDate = new DateTime(2023, 12, 3, 20, 37, 33, 69, DateTimeKind.Local).AddTicks(8025),
                            FatRate = 60.8m,
                            FoodPic = "Images/findik.jpg",
                            Name = "Fındık",
                            PortionDesc = "100 gram",
                            ProteinRate = 15m,
                            Status = 1,
                            Type = 12
                        },
                        new
                        {
                            Id = 39,
                            Calorie = 567m,
                            CarbRate = 16.1m,
                            CreatedDate = new DateTime(2023, 12, 3, 20, 37, 33, 69, DateTimeKind.Local).AddTicks(8026),
                            FatRate = 49.2m,
                            FoodPic = "Images/fistik.jpg",
                            Name = "Fıstık",
                            PortionDesc = "100 gram",
                            ProteinRate = 25.8m,
                            Status = 1,
                            Type = 12
                        },
                        new
                        {
                            Id = 40,
                            Calorie = 52m,
                            CarbRate = 13.8m,
                            CreatedDate = new DateTime(2023, 12, 3, 20, 37, 33, 69, DateTimeKind.Local).AddTicks(8028),
                            FatRate = 0.2m,
                            FoodPic = "yesil_elma.jpg",
                            Name = "Yeşil Elma",
                            PortionDesc = "Adet",
                            ProteinRate = 0.3m,
                            Status = 1,
                            Type = 1
                        },
                        new
                        {
                            Id = 41,
                            Calorie = 546m,
                            CarbRate = 45m,
                            CreatedDate = new DateTime(2023, 12, 3, 20, 37, 33, 69, DateTimeKind.Local).AddTicks(8030),
                            FatRate = 31m,
                            FoodPic = "bitter_cikolata.jpg",
                            Name = "Bitter Çikolata",
                            PortionDesc = "100 gram",
                            ProteinRate = 5m,
                            Status = 1,
                            Type = 13
                        },
                        new
                        {
                            Id = 42,
                            Calorie = 2m,
                            CarbRate = 0m,
                            CreatedDate = new DateTime(2023, 12, 3, 20, 37, 33, 69, DateTimeKind.Local).AddTicks(8031),
                            FatRate = 0m,
                            FoodPic = "Images/turk_kahve.jpg",
                            Name = "Türk Kahvesi",
                            PortionDesc = "Bardak",
                            ProteinRate = 0.1m,
                            Status = 1,
                            Type = 14
                        },
                        new
                        {
                            Id = 43,
                            Calorie = 1m,
                            CarbRate = 0m,
                            CreatedDate = new DateTime(2023, 12, 3, 20, 37, 33, 69, DateTimeKind.Local).AddTicks(8033),
                            FatRate = 0m,
                            FoodPic = "Images/filtre_kahve.jpg",
                            Name = "Filtre Kahve",
                            PortionDesc = "Bardak",
                            ProteinRate = 0.1m,
                            Status = 1,
                            Type = 14
                        });
                });

            modelBuilder.Entity("YemekKalori.Domain.Entities.Meal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("MealCalorie")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("MealTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int?>("Type")
                        .HasColumnType("int");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Meals", (string)null);
                });

            modelBuilder.Entity("YemekKalori.Domain.Entities.MealFood", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<decimal>("Calorie")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CarbRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("FatRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("FoodId")
                        .HasColumnType("int");

                    b.Property<int?>("MealId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Portion")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ProteinRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FoodId");

                    b.HasIndex("MealId");

                    b.ToTable("MealFood", (string)null);
                });

            modelBuilder.Entity("YemekKalori.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<decimal?>("BMI")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("decimal(18,2)")
                        .HasComputedColumnSql("CAST([Weight] / POWER([Height], 2) AS DECIMAL(18,2))", true);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Diet")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("Goal")
                        .HasColumnType("int");

                    b.Property<decimal?>("HedefKalori")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Height")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Salt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal?>("Weight")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2023, 12, 3, 20, 37, 33, 69, DateTimeKind.Local).AddTicks(7079),
                            FirstName = "Admin",
                            Height = 0m,
                            LastName = "Admin",
                            Password = "a1f642e1177cc73abb75a3e1da847ee91d0900418a77b719552e3238f62c79e3",
                            Salt = "OV2VNGJqfU83KJpOhlxjReDDhL0jKibZxtGDDVZP634=",
                            Status = 1,
                            Type = 1,
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("YemekKalori.Domain.Entities.Meal", b =>
                {
                    b.HasOne("YemekKalori.Domain.Entities.User", "User")
                        .WithMany("UserMeals")
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("YemekKalori.Domain.Entities.MealFood", b =>
                {
                    b.HasOne("YemekKalori.Domain.Entities.Food", "Food")
                        .WithMany("MealFoods")
                        .HasForeignKey("FoodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("YemekKalori.Domain.Entities.Meal", "Meal")
                        .WithMany("MealFoods")
                        .HasForeignKey("MealId");

                    b.Navigation("Food");

                    b.Navigation("Meal");
                });

            modelBuilder.Entity("YemekKalori.Domain.Entities.Food", b =>
                {
                    b.Navigation("MealFoods");
                });

            modelBuilder.Entity("YemekKalori.Domain.Entities.Meal", b =>
                {
                    b.Navigation("MealFoods");
                });

            modelBuilder.Entity("YemekKalori.Domain.Entities.User", b =>
                {
                    b.Navigation("UserMeals");
                });
#pragma warning restore 612, 618
        }
    }
}
